#version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: rag_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-rag_chat}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    # host_port:container_port -> container runs MySQL on 3306 always; host port is configurable via MYSQL_PORT_HOST
    ports:
      - "${MYSQL_PORT_HOST:-3306}:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: rag_adminer
    ports:
      - "${ADMINER_PORT_HOST:-8081}:8080"
    depends_on:
      - mysql
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: unless-stopped

  backend:
    build: .
    container_name: rag_backend
    # environment values come from the env file; ensure you pass the correct env file when starting (see .env.dev/.env.prod)
    env_file:
      - .env.dev
    # map host SERVER_PORT to container SERVER_PORT (container must run the app on the same port)
    ports:
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql-data:
